#include "exporter.h"
#include <QTextStream>
#include <QProcess>

namespace wallwatch{

QString Exporter::getExportDir(){
    QString path = QDir::homePath() + "/.local/share/wallwatch/exports/";
    QDir().mkpath(path);
    return path;
}

void Exporter::exportAll(const QJsonObject &root){
    QString base = getExportDir();
    QJsonObject colors = root["colors"].toObject();

    toRust(colors, base);
    toShell(colors, base);
    toXresources(colors, base);
}

void Exporter::toRust(const QJsonObject &colors, const QString &path){
    QSaveFile file(path+ "palette.rs");

    if(file.open(QIODevice::WriteOnly)){
        QTextStream out(&file);
        out << "//Generated by wallwatch\n";
        out << "pub struct Palette{\n";

        for(auto it = colors.begin(); it != colors.end(); ++it){
            out << "    pub " << it.key() << ": &'static str,\n";
        }
        out << "}\n\n";
        out << "pub const THEME: Palette = Palette{\n";

        for(auto it = colors.begin(); it != colors.end(); it++){
            out << "    " << it.key() << ": \"" << it.value().toString() << "\",\n";
        }
        out << "};\n";
        file.commit();
    }
}

void Exporter::toShell(const QJsonObject &colors, const QString &path){
    QSaveFile file(path + "colors.sh");
    if(file.open(QIODevice::WriteOnly)){
        QTextStream out(&file);
        for(auto it = colors.begin(); it != colors.end(); ++it){
            QString key = it.key();
            QString snake;
            for(int i=0; i<key.length(); ++i){
                if(key[i].isUpper()) snake += '_';
                snake += key[i].toUpper();
            }
            out << "export WALLWATCH_" << snake << "=\"" << it.value().toString() << "\"\n";
        }
        file.commit();
    }
}
void Exporter::toXresources(const QJsonObject &colors, const QString &path){
    QString filePath = path + ".Xresources";
    QSaveFile file(filePath);
    if(file.open(QIODevice::WriteOnly)){
        QTextStream out(&file);
        out << "! Generated by wallwatch.\n";
        out << "*.foreground: " << colors["onSurface"].toString() << " ! Primary Text\n";
        out << "*.background: " << colors["surface"].toString() << " ! Main Background\n";
        out << "*.cursorColor: " << colors["primary"].toString() << " ! Cursor Accent\n";
        out << "*.color0: " << colors["surfaceContainerLowest"].toString() << " ! Black (Base)\n";
        out << "*.color8: " << colors["outlineVariant"].toString() << " ! Black (Bright)\n";
        out << "*.color1: " << colors["error"].toString() << " ! Red (Base)\n";
        out << "*.color9: " << colors["errorContainer"].toString() << " ! Red (Bright)\n";
        out << "*.color2: " << colors["success"].toString() << " ! Green (Base)\n";
        out << "*.color10: " << colors["successContainer"].toString() << " ! Green (Bright)\n";
        out << "*.color3: " << colors["tertiary"].toString() << " ! Yellow (Base)\n";
        out << "*.color11: " << colors["tertiaryContainer"].toString() << " ! Yellow (Bright)\n";
        out << "*.color4: " << colors["primary"].toString() << " ! Blue (Base)\n";
        out << "*.color12: " << colors["primaryContainer"].toString() << " ! Blue (Bright)\n";
        out << "*.color5: " << colors["outline"].toString() << " ! Magenta (Base)\n";
        out << "*.color13: " << colors["surfaceVariant"].toString() << " ! Magenta (Bright)\n";
        out << "*.color6: " << colors["secondary"].toString() << " ! Cyan (Base)\n";
        out << "*.color14: " << colors["secondaryContainer"].toString() << " ! Cyan (Bright)\n";
        out << "*.color7: " << colors["onSurfaceVariant"].toString() << " ! White (Base)\n";
        out << "*.color15: " << colors["onSurface"].toString() << " ! White (Bright)\n";
        if(file.commit()){
            QProcess::execute("xrdb", {"-merge", filePath});
        }
    }
}
}  //namespace wallwatch
