function(wallwatch_module TARGET)
    cmake_parse_arguments(PARSE_ARGV 1 arg "" "OUTPUT_DIR" "SOURCES;LIBRARIES;INCLUDES")
    if(arg_SOURCES)
        if(${TARGET} STREQUAL "wallwatch")
            add_executable(${TARGET} ${arg_SOURCES})
            target_link_libraries(${TARGET} PRIVATE ${OpenCV_LIBRARIES})
            if(arg_LIBRARIES)
                target_link_libraries(${TARGET} PRIVATE ${arg_LIBRARIES})
            endif()
        else()
            add_library(${TARGET} STATIC ${arg_SOURCES})
            if(arg_LIBRARIES)
                target_link_libraries(${TARGET} PRIVATE ${arg_LIBRARIES})
            endif()
        endif()
    else()
        message(FATAL_ERROR "No SOURCES provided for target ${TARGET}")
    endif()
    if(arg_INCLUDES)
        target_include_directories(${TARGET} PRIVATE ${arg_INCLUDES})
    endif()
    if(arg_OUTPUT_DIR)
        install(TARGETS ${TARGET}
            RUNTIME DESTINATION ${arg_OUTPUT_DIR}
            LIBRARY DESTINATION ${arg_OUTPUT_DIR}
        )
        message(STATUS "Installing ${TARGET} to ${arg_OUTPUT_DIR}")
    endif()
    if(arg_LIBRARIES)
        message(STATUS "*Linked:")
        foreach(lib ${arg_LIBRARIES})
            message(STATUS "    ${lib}")
        endforeach()
    endif()
endfunction()
